os: linux
dist: xenial
services:
  - docker
language: python
python:
  - "3.9"
before_install:
  - python3 -m pip install --upgrade pip setuptools wheel
install:
  - if [[ -n "${DOCKERHUB_TOKEN:-}" ]]; then docker login -u nextstrainbot --password-stdin <<<"$DOCKERHUB_TOKEN"; fi
  - pip3 install git+https://github.com/nextstrain/cli
  - nextstrain version
  - nextstrain check-setup
  - nextstrain update
  - pip3 install cram nextstrain-augur
script:
  - gunzip data/example_sequences.fasta.gz
  - nextstrain build . all_regions -j 2 --profile nextstrain_profiles/nextstrain-ci
  - cram --shell=/bin/bash tests/sanitize-metadata.t
